openconfig-interfaces:interfaces:
  interface:
  - config:
      description: ''
      enabled: 'True'
      loopback-mode: 'False'
      mtu: ''
      name: ''
      type: ''
    hold-time:
      config:
        down: '0'
        up: '0'
      state:
        down: '0'
        up: '0'
    name: ''
    state:
      admin-status: ''
      counters:
        carrier-transitions: ''
        in-broadcast-pkts: ''
        in-discards: ''
        in-errors: ''
        in-fcs-errors: ''
        in-multicast-pkts: ''
        in-octets: ''
        in-pkts: ''
        in-unicast-pkts: ''
        in-unknown-protos: ''
        last-clear: ''
        out-broadcast-pkts: ''
        out-discards: ''
        out-errors: ''
        out-multicast-pkts: ''
        out-octets: ''
        out-pkts: ''
        out-unicast-pkts: ''
      cpu: ''
      description: ''
      enabled: 'True'
      ifindex: ''
      last-change: ''
      logical: ''
      loopback-mode: 'False'
      management: ''
      mtu: ''
      name: ''
      oper-status: ''
      type: ''
    subinterfaces:
      subinterface:
      - config:
          description: ''
          enabled: 'True'
          index: '0'
        index: ''
        state:
          admin-status: ''
          counters:
            carrier-transitions: ''
            in-broadcast-pkts: ''
            in-discards: ''
            in-errors: ''
            in-fcs-errors: ''
            in-multicast-pkts: ''
            in-octets: ''
            in-pkts: ''
            in-unicast-pkts: ''
            in-unknown-protos: ''
            last-clear: ''
            out-broadcast-pkts: ''
            out-discards: ''
            out-errors: ''
            out-multicast-pkts: ''
            out-octets: ''
            out-pkts: ''
            out-unicast-pkts: ''
          cpu: ''
          description: ''
          enabled: 'True'
          ifindex: ''
          index: '0'
          last-change: ''
          logical: ''
          management: ''
          name: ''
          oper-status: ''
