openconfig-system:system:
  aaa:
    accounting:
      config:
        accounting-method:
        - '['
        - ']'
      events:
        event:
        - config:
            event-type: ''
            record: ''
          event-type: ''
          state:
            event-type: ''
            record: ''
      state:
        accounting-method:
        - '['
        - ']'
    authentication:
      admin-user:
        config:
          admin-password: ''
          admin-password-hashed: ''
        state:
          admin-password: ''
          admin-password-hashed: ''
          admin-username: ''
      config:
        authentication-method:
        - '['
        - ']'
      state:
        authentication-method:
        - '['
        - ']'
      users:
        user:
        - config:
            password: ''
            password-hashed: ''
            role: ''
            ssh-key: ''
            username: ''
          state:
            password: ''
            password-hashed: ''
            role: ''
            ssh-key: ''
            username: ''
          username: ''
    authorization:
      config:
        authorization-method:
        - '['
        - ']'
      events:
        event:
        - config:
            event-type: ''
          event-type: ''
          state:
            event-type: ''
      state:
        authorization-method:
        - '['
        - ']'
    config: {}
    server-groups:
      server-group:
      - config:
          name: ''
          type: ''
        name: ''
        servers:
          server:
          - address: ''
            config:
              address: ''
              name: ''
              timeout: ''
            radius:
              config:
                acct-port: '1813'
                auth-port: '1812'
                retransmit-attempts: ''
                secret-key: ''
                source-address: ''
              state:
                acct-port: '1813'
                auth-port: '1812'
                counters:
                  access-accepts: ''
                  access-rejects: ''
                  retried-access-requests: ''
                  timeout-access-requests: ''
                retransmit-attempts: ''
                secret-key: ''
                source-address: ''
            state:
              address: ''
              connection-aborts: ''
              connection-closes: ''
              connection-failures: ''
              connection-opens: ''
              connection-timeouts: ''
              errors-received: ''
              messages-received: ''
              messages-sent: ''
              name: ''
              timeout: ''
            tacacs:
              config:
                port: '49'
                secret-key: ''
                source-address: ''
              state:
                port: '49'
                secret-key: ''
                source-address: ''
        state:
          name: ''
          type: ''
    state: {}
  alarms:
    alarm:
    - config:
        id: ''
      id: ''
      state:
        id: ''
        resource: ''
        severity: ''
        text: ''
        time-created: ''
        type-id: ''
  clock:
    config:
      timezone-name: ''
    state:
      timezone-name: ''
  config:
    domain-name: ''
    hostname: ''
    login-banner: ''
    motd-banner: ''
  cpus:
    cpu:
    - index: ''
      state:
        hardware-interrupt:
          avg: ''
          instant: ''
          interval: ''
          max: ''
          max-time: ''
          min: ''
          min-time: ''
        idle:
          avg: ''
          instant: ''
          interval: ''
          max: ''
          max-time: ''
          min: ''
          min-time: ''
        index: ''
        kernel:
          avg: ''
          instant: ''
          interval: ''
          max: ''
          max-time: ''
          min: ''
          min-time: ''
        nice:
          avg: ''
          instant: ''
          interval: ''
          max: ''
          max-time: ''
          min: ''
          min-time: ''
        software-interrupt:
          avg: ''
          instant: ''
          interval: ''
          max: ''
          max-time: ''
          min: ''
          min-time: ''
        total:
          avg: ''
          instant: ''
          interval: ''
          max: ''
          max-time: ''
          min: ''
          min-time: ''
        user:
          avg: ''
          instant: ''
          interval: ''
          max: ''
          max-time: ''
          min: ''
          min-time: ''
        wait:
          avg: ''
          instant: ''
          interval: ''
          max: ''
          max-time: ''
          min: ''
          min-time: ''
  dns:
    config:
      search:
      - '['
      - ']'
    host-entries:
      host-entry:
      - config:
          alias:
          - '['
          - ']'
          hostname: ''
          ipv4-address:
          - '['
          - ']'
          ipv6-address:
          - '['
          - ']'
        hostname: ''
        state:
          alias:
          - '['
          - ']'
          hostname: ''
          ipv4-address:
          - '['
          - ']'
          ipv6-address:
          - '['
          - ']'
    servers:
      server:
      - address: ''
        config:
          address: ''
          port: '53'
        state:
          address: ''
          port: '53'
    state:
      search:
      - '['
      - ']'
  grpc-server:
    config:
      certificate-id: ''
      enable: 'True'
      listen-addresses:
      - '['
      - ']'
      port: '9339'
      transport-security: ''
    state:
      certificate-id: ''
      enable: 'True'
      listen-addresses:
      - '['
      - ']'
      port: '9339'
      transport-security: ''
  logging:
    console:
      config: {}
      selectors:
        selector:
        - config:
            facility: ''
            severity: ''
          facility: ''
          severity: ''
          state:
            facility: ''
            severity: ''
      state: {}
    remote-servers:
      remote-server:
      - config:
          host: ''
          remote-port: '514'
          source-address: ''
        host: ''
        selectors:
          selector:
          - config:
              facility: ''
              severity: ''
            facility: ''
            severity: ''
            state:
              facility: ''
              severity: ''
        state:
          host: ''
          remote-port: '514'
          source-address: ''
  memory:
    config: {}
    state:
      physical: ''
      reserved: ''
  ntp:
    config:
      enable-ntp-auth: 'False'
      enabled: 'False'
      ntp-source-address: ''
    ntp-keys:
      ntp-key:
      - config:
          key-id: ''
          key-type: ''
          key-value: ''
        key-id: ''
        state:
          key-id: ''
          key-type: ''
          key-value: ''
    servers:
      server:
      - address: ''
        config:
          address: ''
          association-type: SERVER
          iburst: 'False'
          port: '123'
          prefer: 'False'
          version: '4'
        state:
          address: ''
          association-type: SERVER
          iburst: 'False'
          offset: ''
          poll-interval: ''
          port: '123'
          prefer: 'False'
          root-delay: ''
          root-dispersion: ''
          stratum: ''
          version: '4'
    state:
      auth-mismatch: ''
      enable-ntp-auth: 'False'
      enabled: 'False'
      ntp-source-address: ''
  processes:
    process:
    - pid: ''
      state:
        args:
        - '['
        - ']'
        cpu-usage-system: ''
        cpu-usage-user: ''
        cpu-utilization: ''
        memory-usage: ''
        memory-utilization: ''
        name: ''
        pid: ''
        start-time: ''
        uptime: ''
  ssh-server:
    config:
      enable: 'True'
      protocol-version: V2
      rate-limit: ''
      session-limit: ''
      timeout: ''
    state:
      enable: 'True'
      protocol-version: V2
      rate-limit: ''
      session-limit: ''
      timeout: ''
  state:
    boot-time: ''
    current-datetime: ''
    domain-name: ''
    hostname: ''
    login-banner: ''
    motd-banner: ''
  telnet-server:
    config:
      enable: 'False'
      rate-limit: ''
      session-limit: ''
      timeout: ''
    state:
      enable: 'False'
      rate-limit: ''
      session-limit: ''
      timeout: ''
