oc-interfaces-nso:oc-interfaces-nso:
  - name: s1
    device: s1
    openconfig-interfaces:
      interfaces:
        interface:
#        - config:
#            description: 'Example Routed Vlan10 DHCP'
#            enabled: true
#            name: 'Vlan10'
#            type: 'l3ipvlan'
#          name: 'Vlan10'
#          routed-vlan:
#            config:
#              vlan: '10'
#            ipv4:
#              config:
#                dhcp-client: true
#        - config:
#            description: 'Example Routed Vlan100 IP'
#            enabled: true
#            loopback-mode: false
#            mtu: '1500'
#            name: 'Vlan100'
#            type: 'l3ipvlan'
#          name: 'Vlan100'
#          routed-vlan:
#            config:
#              vlan: '100'
#            ipv4:
#              addresses:
#                address:
#                - config:
#                    ip: '192.168.100.1'
#                    prefix-length: '24'
#                  ip: '192.168.100.1'
#              proxy-arp:
#                config:
#                  mode: DISABLE  # Default is DISABLE other option is REMOTE_ONLY for IOS
#        - config:
#            description: 'Trunk Port Example'
#            enabled: true
#            name: 'GigabitEthernet0/1'
#            type: 'l2vlan'
#          ethernet:
#            config:
#              auto-negotiate: true
#              enable-flow-control: true
#            switched-vlan:
#              config:
#                interface-mode: 'TRUNK'
#                native-vlan: '99'
#                trunk-vlans:
#                - '100'
#                - '200'
#                - '300'
##                - '400'
#          hold-time:
#            config:
#              down: '0'  # in msec
#              up: '0'  # not in xe
#          name: 'GigabitEthernet0/1'
#        - config:
#            description: 'Access Port Example'
#            enabled: true
#            loopback-mode: false
#            name: 'GigabitEthernet0/2'
#            type: 'l2vlan'
#          ethernet:
#            config:
#              auto-negotiate: true
#              enable-flow-control: false
##              mac-address: ''  # VV:VV:VV:SS:SS:SS
#            switched-vlan:
#              config:
#                access-vlan: '100'
#                interface-mode: 'ACCESS'
#          hold-time:
#            config:
#              down: '0'
#              up: '0'
#          name: 'GigabitEthernet0/2'
#        - aggregation:
#            config:
#              lag-type: 'LACP'
#            switched-vlan:
#              config:
#                interface-mode: 'TRUNK'
##                native-vlan: '99'  # when interface-mode = TRUNK
#                trunk-vlans:
#                - '100'
#                - '200'
#                - '300'
#                - '500'
#          config:
#            description: 'LACP Example PO1'
#            enabled: true
#            mtu: '1500'
#            name: 'port-channel1'
#            type: 'ieee8023adLag'
#          name: 'port-channel1'
#        - aggregation:
#            config:
#              lag-type: 'LACP'
#            ipv4:
#              addresses:
#                address:
#                  - config:
#                      ip: '192.168.50.1'
#                      prefix-length: '24'
#                    ip: '192.168.50.1'
#          config:
#            description: 'LACP Example PO2'
#            enabled: true
#            mtu: '1500'
#            name: 'port-channel2'
#            type: 'ieee8023adLag'
#          hold-time:
#            config:
#              down: '10'  # in msec
#              up: '0'  # not in xe
#          name: 'port-channel2'

#        - config:
#            description: 'LACP Link Trunk Port Example'
#            enabled: true
#            mtu: '1500'
#            name: 'GigabitEthernet0/3'
#            type: 'ethernetCsmacd'
#          ethernet:
#            config:
#              aggregate-id: 'port-channel1'
#              auto-negotiate: true
#              duplex-mode: 'FULL'
#              enable-flow-control: false
#            switched-vlan:
#              config:
#                interface-mode: 'TRUNK'
#                native-vlan: '99'
#                trunk-vlans:
#                - '100'
#                - '200'
#                - '300'
#          hold-time:
#            config:
#              down: '0'
#              up: '0'
#          name: 'GigabitEthernet0/3'
        - config:
            description: 'Physical Interface 1'
            enabled: true
            mtu: '1500'
            name: 'GigabitEthernet0/2'
            type: 'ethernetCsmacd'
          ethernet:
            config:
              auto-negotiate: true
              enable-flow-control: false
          hold-time:
            config:
              down: '10'
              up: '0'
          name: 'GigabitEthernet0/2'
          subinterfaces:
            subinterface:
            - config:
                index: '0'
              index: '0'
              ipv4:
                addresses:
                  address:
                    - config:
                        ip: '192.168.111.1'
                        prefix-length: '24'
                      ip: '192.168.111.1'
                config:
                  dhcp-client: false
        - config:
            description: 'Physical Interface 2'
            enabled: true
            mtu: '1500'
            name: 'GigabitEthernet0/3'
            type: 'ethernetCsmacd'
          ethernet:
            config:
              auto-negotiate: true
          hold-time:
            config:
              down: '10'
              up: '0'
          name: 'GigabitEthernet0/3'
          subinterfaces:
            subinterface:
            - config:
                description: 'Sub interface 5'
                enabled: true
                index: '5'
              index: '5'
              ipv4:
                addresses:
                  address:
                  - config:
                      ip: '192.168.104.2'
                      prefix-length: '24'
                    ip: '192.168.104.2'
                config:
                  dhcp-client: false
                  enabled: true
                  mtu: '1500'
                proxy-arp:
                  config:
                    mode: DISABLE
              vlan:
                config:
                  vlan-id: '100'
            - config:
                description: 'Sub interface 6'
                enabled: true
                index: '6'
              index: '6'
              ipv4:
                addresses:
                  address:
                  - config:
                      ip: '192.168.106.2'
                      prefix-length: '24'
                    ip: '192.168.106.2'
                    vrrp:
                      vrrp-group:
                        - config:
                            advertisement-interval: '300'  # units "centiseconds"; vrrp 5 timers advertise 3
                            preempt: true
                            preempt-delay: '10'  # vrrp 5 preempt delay minimum 100
                            priority: '200'  # vrrp 5 priority 200
                            virtual-address:  # vrrp 5 ip 192.168.106.200
                              - '192.168.106.200'
                            virtual-router-id: '5'  # group number
                          virtual-router-id: '5'  # group number
                config:
                  dhcp-client: false
                  enabled: true
                  mtu: '1500'
                proxy-arp:
                  config:
                    mode: DISABLE
              vlan:
                config:
                  vlan-id: '200'