oc-system-nso:oc-system-nso:
  - name: hq-rtr1
    device: hq-rtr1
    openconfig-system:
      system:
        aaa:
          accounting:
            config:
              accounting-method:  # group name, TACACS_ALL
#                - 'TACACS_ALL'
                - 'TACACS-GROUP-1'
            events:
              event:  # OC supports command and login
                - config:
                    event-type: 'AAA_ACCOUNTING_EVENT_LOGIN'  # IOS aaa accounting exec for ios
                    record: 'STOP'  # or START_STOP
                  event-type: 'AAA_ACCOUNTING_EVENT_LOGIN'
                - config:
                    event-type: 'AAA_ACCOUNTING_EVENT_COMMAND'  # IOS aaa accounting commanda and priv 15
                    record: 'STOP'  # or START_STOP
                  event-type: 'AAA_ACCOUNTING_EVENT_COMMAND'
          authentication:
            admin-user:
              config:
                admin-password: 'admin'
                admin-password-hashed: ''
            config:
              authentication-method:
#                - 'TACACS_ALL'
                - 'LOCAL'
            users:
              user:
                - config:
                    username: 'user1'
                    password: 'Password123'
                    password-hashed: ''
                    role: 'SYSTEM_ROLE_ADMIN'  # This is the one role in model
                    ssh-key: ''
                  username: 'user1'
                - config:
                    username: 'user2'
                    password: 'Password123'
                    password-hashed: ''
                    role: 'SYSTEM_ROLE_ADMIN'  # This is the one role in model
                    ssh-key: ''
                  username: 'user2'
          authorization:
            config:
              authorization-method:
#                - 'TACACS_ALL'
                - 'LOCAL'
            events:
              event:
                - config:
                    event-type: 'AAA_AUTHORIZATION_EVENT_CONFIG'  # Specifies configuration (e.g., EXEC) events for AAA
                  event-type: 'AAA_AUTHORIZATION_EVENT_CONFIG'
#                - config:
#                    event-type: 'AAA_AUTHORIZATION_EVENT_COMMAND'  # Specifies interactive command events for AAA authorization
#                  event-type: 'AAA_AUTHORIZATION_EVENT_COMMAND'
          config: { }
          server-groups:
            server-group:
              - config:
                  name: 'TACACS-GROUP-1'
                  type: 'TACACS'
                name: 'TACACS-GROUP-1'
                servers:
                  server:
                    - address: '10.1.1.1'
                      config:
                        address: '10.1.1.1'
                        name: 'TACACSSVR1'
                        timeout: '10'
                      tacacs:
                        config:
                          port: '49'
                          secret-key: 'Password123'
                          source-address: '172.16.255.1'  # For each group, sources must be the same
                    - address: '10.2.2.2'
                      config:
                        address: '10.2.2.2'
                        name: 'TACACSSVR2'
                        timeout: '10'
                      tacacs:
                        config:
                          port: '49'
                          secret-key: 'Password123'
                          source-address: '172.16.255.1'  # For each group, sources must be the same
              - config:
                  name: 'TACACS-GROUP-2'
                  type: 'TACACS'
                name: 'TACACS-GROUP-2'
                servers:
                  server:
                    - address: '10.3.3.3'
                      config:
                        address: '10.3.3.3'
                        name: 'TACACSSVR3'
                        timeout: '10'
                      tacacs:
                        config:
                          port: '49'
                          secret-key: 'Password123'
                          source-address: '172.16.0.2'  # For each group, sources must be the same
                    - address: '10.4.4.4'
                      config:
                        address: '10.4.4.4'
                        name: 'TACACSSVR4'
                        timeout: '10'
                      tacacs:
                        config:
                          port: '49'
                          secret-key: 'Password123'
                          source-address: '172.16.0.2'  # For each group, sources must be the same
        clock:
          config:
            timezone-name: 'EDT -4 0'
        config:
          nso-enable-secret: 'admin'
          nso-console-exec-timeout-seconds: '600'
          domain-name: 'cisco.com'
          hostname: 'hq-rtr1'
          login-banner: |
            This is line 1.
            This is line 2.
            This is the last line.
          motd-banner: |
            This is line 1.
            This is line 2.
            This is the last line.
        dns:
          servers:
            server:
              - address: '8.8.8.8'
                config:
                  address: '8.8.8.8'
                  port: '53'  # always 53 for ios
              - address: '8.8.4.4'
                config:
                  address: '8.8.4.4'
                  port: '53'  # always 53 for ios
        logging:  # facility must be same for all in IOS
          console:  # set console and monitor
            config: { }
            selectors:
              selector:
                - config:
                    facility: 'SYSLOG'
                    severity: 'INFORMATIONAL'  # logging console & logging monitor
                  facility: 'SYSLOG'
                  severity: 'INFORMATIONAL'
          remote-servers:
            remote-server:
              - config:
                  host: '10.0.0.1'  # logging host x.x.x.x
                  remote-port: '514'
                  source-address: '172.16.255.1'  # logging source-interface Loopback0; same for all servers
                  nso-use-vrf: ''  # '' for default or VRF eg Mgmt-intf
                host: '10.0.0.1'
                selectors:
                  selector:
                    - config:
                        facility: 'SYSLOG'
                        severity: 'INFORMATIONAL'
                      facility: 'SYSLOG'
                      severity: 'INFORMATIONAL'
              - config:
                  host: '10.0.0.2'  # logging host x.x.x.x
                  remote-port: '514'
                  source-address: '172.16.255.1'  # logging source-interface Loopback0; same for all servers
                  nso-use-vrf: ''  # '' for default or VRF eg Mgmt-intf
                host: '10.0.0.2'
                selectors:
                  selector:
                    - config:
                        facility: 'SYSLOG'
                        severity: 'INFORMATIONAL'
                      facility: 'SYSLOG'
                      severity: 'INFORMATIONAL'
        ntp:
          config:
            nso-ntp-enable-logging: true
            enable-ntp-auth: true
            enabled: true  # true or false - removes or adds ntp servers
            ntp-source-address: '172.16.255.1'
          ntp-keys:
            ntp-key:
            - config:
                key-id: '1'
                key-type: 'NTP_AUTH_MD5'
                key-value: 'password1'
              key-id: '1'
            - config:
                key-id: '2'
                key-type: 'NTP_AUTH_MD5'
                key-value: 'password2'
              key-id: '2'
          servers:
            server:
              - address: '10.0.0.1'
                nso-ntp-use-vrf: ''  # '' for default
                config:
                  nso-ntp-auth-key-id: '1'
                  address: '10.0.0.1'
                  association-type: SERVER  # SERVER, PEER, POOL
                  iburst: true
                  port: '123'  # always 123 for ios
                  prefer: false
                  version: '4'
              - address: '10.0.0.2'
                nso-ntp-use-vrf: 'Mgmt-intf'  # '' for default
                config:
                  nso-ntp-auth-key-id: ''
                  address: '10.0.0.2'
                  association-type: SERVER  # SERVER, PEER, POOL
                  iburst: true
                  port: '123'  # always 123 for ios
                  prefer: false
                  version: '4'
        ssh-server:
          config:
            nso-absolute-timeout-minutes: '1200'
            nso-ssh-timeout: '60'  # ip ssh timeout
            nso-ssh-source-interface: 'GigabitEthernet8'
            enable: true  #   adds line transport input ssh; must be enabled for this to work
            protocol-version: 'V2'  # ip ssh version 2
            rate-limit: '0'  # unsupported in ios
            session-limit: '16' # line session-limit 16
            timeout: '1800'  # seconds - line exec-timeout 30 0
