mdd:openconfig:
  openconfig-interfaces:interfaces:
    interface:
      - config:
          description: 'Example Routed Vlan10 DHCP'
          enabled: true
          name: 'Vlan10'
          type: 'l3ipvlan'
        name: 'Vlan10'
        openconfig-vlan:routed-vlan:
          config:
            vlan: '10'
          openconfig-if-ip:ipv4:
            config:
              dhcp-client: true
      - config:
          description: 'Example Routed Vlan100 IP'
          enabled: true
          loopback-mode: false
          mtu: '1500'
          name: 'Vlan100'
          type: 'l3ipvlan'
        name: 'Vlan100'
        openconfig-vlan:routed-vlan:
          config:
            vlan: '100'
          openconfig-if-ip:ipv4:
            addresses:
              address:
                - config:
                    ip: '192.168.100.1'
                    prefix-length: '24'
                  ip: '192.168.100.1'
            proxy-arp:
              config:
                mode: DISABLE  # Default is DISABLE other option is REMOTE_ONLY for IOS
      - config:
          description: 'Trunk Port Example'
          enabled: true
          name: 'GigabitEthernet0/1'
          type: 'l2vlan'
        openconfig-if-ethernet:ethernet:
          config:
            auto-negotiate: true
            enable-flow-control: true
          openconfig-vlan:switched-vlan:
            config:
              interface-mode: 'TRUNK'
              native-vlan: '99'
              trunk-vlans:
                - '100'
                - '200'
                - '300'
                - '400'
        hold-time:
          config:
            down: '0'  # in msec
            up: '0'  # not in xe
        name: 'GigabitEthernet0/1'
      - config:
          description: 'Access Port Example'
          enabled: true
          loopback-mode: false
          name: 'GigabitEthernet0/2'
          type: 'l2vlan'
        openconfig-if-ethernet:ethernet:
          config:
            auto-negotiate: true
            enable-flow-control: false
    #              mac-address: ''  # VV:VV:VV:SS:SS:SS
          openconfig-vlan:switched-vlan:
            config:
              access-vlan: '100'
              interface-mode: 'ACCESS'
        hold-time:
          config:
            down: '0'
            up: '0'
        name: 'GigabitEthernet0/2'
      - openconfig-if-aggregate:aggregation:
          config:
            lag-type: 'LACP'
          openconfig-vlan:switched-vlan:
            config:
              interface-mode: 'TRUNK'
    #                native-vlan: '99'  # when interface-mode = TRUNK
              trunk-vlans:
                - '100'
                - '200'
                - '300'
                - '500'
        config:
          description: 'LACP Example PO1'
          enabled: true
          mtu: '1500'
          name: 'port-channel1'
          type: 'ieee8023adLag'
        name: 'port-channel1'
      - openconfig-if-aggregate:aggregation:
          config:
            lag-type: 'LACP'
          openconfig-if-ip:ipv4:
            addresses:
              address:
                - config:
                    ip: '192.168.50.1'
                    prefix-length: '24'
                  ip: '192.168.50.1'
        config:
          description: 'LACP Example PO2'
          enabled: true
          mtu: '1500'
          name: 'port-channel2'
          type: 'ieee8023adLag'
        hold-time:
          config:
            down: '10'  # in msec
            up: '0'  # not in xe
        name: 'port-channel2'

      - config:
          description: 'LACP Link Trunk Port Example'
          enabled: true
          mtu: '1500'
          name: 'GigabitEthernet1/1'
          type: 'ethernetCsmacd'
        openconfig-if-ethernet:ethernet:
          config:
            openconfig-if-aggregate:aggregate-id: 'port-channel1'
            auto-negotiate: true
            duplex-mode: 'FULL'
            enable-flow-control: false
          openconfig-vlan:switched-vlan:
            config:
              interface-mode: 'TRUNK'
              native-vlan: '99'
              trunk-vlans:
                - '100'
                - '200'
                - '300'
        hold-time:
          config:
            down: '0'
            up: '0'
        name: 'GigabitEthernet1/1'
      - config:
          description: 'Physical Interface 1/0'
          enabled: true
          mtu: '1500'
          name: 'GigabitEthernet1/0'
          type: 'ethernetCsmacd'
        openconfig-if-ethernet:ethernet:
          config:
            auto-negotiate: true
            enable-flow-control: false
        hold-time:
          config:
            down: '10'
            up: '0'
        name: 'GigabitEthernet1/0'
        subinterfaces:
          subinterface:
            - config:
                index: '0'
              index: '0'
              openconfig-if-ip:ipv4:
                addresses:
                  address:
                    - config:
                        ip: '192.168.111.1'
                        prefix-length: '24'
                      ip: '192.168.111.1'
                config:
                  dhcp-client: false
      - config:
          description: 'Physical Interface 1/1'
          enabled: true
          mtu: '1500'
          name: 'GigabitEthernet1/1'
          type: 'ethernetCsmacd'
        openconfig-if-ethernet:ethernet:
          config:
            auto-negotiate: true
        hold-time:
          config:
            down: '10'
            up: '0'
        name: 'GigabitEthernet1/1'
        subinterfaces:
          subinterface:
            - config:
                description: 'Sub interface 5'
                enabled: true
                index: '5'
              index: '5'
              openconfig-if-ip:ipv4:
                addresses:
                  address:
                    - config:
                        ip: '192.168.104.2'
                        prefix-length: '24'
                      ip: '192.168.104.2'
                config:
                  dhcp-client: false
                  enabled: true
                  mtu: '1500'
                proxy-arp:
                  config:
                    mode: DISABLE
              openconfig-vlan:vlan:
                config:
                  vlan-id: '100'
            - config:
                description: 'Sub interface 6'
                enabled: true
                index: '6'
              index: '6'
              openconfig-if-ip:ipv4:
                addresses:
                  address:
                    - config:
                        ip: '192.168.106.2'
                        prefix-length: '24'
                      ip: '192.168.106.2'
                      vrrp:
                        vrrp-group:
                          - config:
                              advertisement-interval: '300'  # units "centiseconds"; vrrp 5 timers advertise 3
                              preempt: true
                              preempt-delay: '10'  # vrrp 5 preempt delay minimum 100
                              priority: '200'  # vrrp 5 priority 200
                              virtual-address:  # vrrp 5 ip 192.168.106.200
                                - '192.168.106.200'
                              virtual-router-id: '5'  # group number
                            virtual-router-id: '5'  # group number
                config:
                  dhcp-client: false
                  enabled: true
                  mtu: '1500'
                proxy-arp:
                  config:
                    mode: DISABLE
              openconfig-vlan:vlan:
                config:
                  vlan-id: '200'

  openconfig-network-instance:network-instances:
    network-instance:
      - name: 'default'  # All interfaces are in default unless listed under other VRF
        config:
          name: 'default'
          type: 'DEFAULT_INSTANCE'  # oc-ni-types:DEFAULT_INSTANCE
          enabled: true
      - name: 'abc'
        config:
          name: 'abc'
          type: 'L3VRF'  # oc-ni-types:DEFAULT_INSTANCE
          enabled: true  # not in IOS
          enabled-address-families:
            - 'IPV4'
        interfaces:
          interface:
            - id: 'GigabitEthernet1/1.6'
              config:
                id: 'GigabitEthernet1/1.6'
                interface: 'GigabitEthernet1/1'
                subinterface: '6'
      - name: 'def'
        config:
          name: 'def'
          type: 'L3VRF'  # oc-ni-types:DEFAULT_INSTANCE
          enabled: true  # not in IOS
          enabled-address-families:
            - 'IPV4'
      - name: 'ghi'
        config:
          name: 'ghi'
          type: 'L3VRF'  # oc-ni-types:DEFAULT_INSTANCE
          enabled: true  # not in IOS
          enabled-address-families:
            - 'IPV4'
      - name: 'lmnop'
        config:
          name: 'lmnop'
          type: 'L3VRF'  # oc-ni-types:DEFAULT_INSTANCE
          enabled: true  # not in IOS
          enabled-address-families:
            - 'IPV4'
  openconfig-system:system:
    aaa:
      accounting:
        config:
          accounting-method:  # group name, TACACS_ALL
#                - 'TACACS_ALL'
            - 'TACACS-GROUP-1'
        events:
          event:  # OC supports command and login
            - config:
                event-type: 'AAA_ACCOUNTING_EVENT_LOGIN'  # IOS aaa accounting exec for ios
                record: 'STOP'  # or START_STOP
              event-type: 'AAA_ACCOUNTING_EVENT_LOGIN'
            - config:
                event-type: 'AAA_ACCOUNTING_EVENT_COMMAND'  # IOS aaa accounting commanda and priv 15
                record: 'STOP'  # or START_STOP
              event-type: 'AAA_ACCOUNTING_EVENT_COMMAND'
      authentication:
        admin-user:
          config:
            admin-password: 'admin'
            admin-password-hashed: ''
        config:
          authentication-method:
#                - 'TACACS_ALL'
            - 'LOCAL'
        users:
          user:
            - config:
                username: 'user1'
                password: 'Password123'
                password-hashed: ''
                role: 'SYSTEM_ROLE_ADMIN'  # This is the one role in model
                ssh-key: ''
              username: 'user1'
            - config:
                username: 'user2'
                password: 'Password123'
                password-hashed: ''
                role: 'SYSTEM_ROLE_ADMIN'  # This is the one role in model
                ssh-key: ''
              username: 'user2'
      authorization:
        config:
          authorization-method:
#                - 'TACACS_ALL'
            - 'LOCAL'
        events:
          event:
            - config:
                event-type: 'AAA_AUTHORIZATION_EVENT_CONFIG'  # Specifies configuration (e.g., EXEC) events for AAA
              event-type: 'AAA_AUTHORIZATION_EVENT_CONFIG'
#                - config:
#                    event-type: 'AAA_AUTHORIZATION_EVENT_COMMAND'  # Specifies interactive command events for AAA authorization
#                  event-type: 'AAA_AUTHORIZATION_EVENT_COMMAND'
      config: { }
      server-groups:
        server-group:
          - config:
              name: 'TACACS-GROUP-1'
              type: 'TACACS'
            name: 'TACACS-GROUP-1'
            servers:
              server:
                - address: '10.1.1.1'
                  config:
                    address: '10.1.1.1'
                    name: 'TACACSSVR1'
                    timeout: '10'
                  tacacs:
                    config:
                      port: '49'
                      secret-key: 'Password123'
                      source-address: '192.168.100.1'  # For each group, sources must be the same
                - address: '10.2.2.2'
                  config:
                    address: '10.2.2.2'
                    name: 'TACACSSVR2'
                    timeout: '10'
                  tacacs:
                    config:
                      port: '49'
                      secret-key: 'Password123'
                      source-address: '192.168.100.1'  # For each group, sources must be the same
          - config:
              name: 'TACACS-GROUP-2'
              type: 'TACACS'
            name: 'TACACS-GROUP-2'
            servers:
              server:
                - address: '10.3.3.3'
                  config:
                    address: '10.3.3.3'
                    name: 'TACACSSVR3'
                    timeout: '10'
                  tacacs:
                    config:
                      port: '49'
                      secret-key: 'Password123'
                      source-address: '192.168.100.1'  # For each group, sources must be the same
                - address: '10.4.4.4'
                  config:
                    address: '10.4.4.4'
                    name: 'TACACSSVR4'
                    timeout: '10'
                  tacacs:
                    config:
                      port: '49'
                      secret-key: 'Password123'
                      source-address: '192.168.100.1'  # For each group, sources must be the same
    clock:
      config:
        timezone-name: 'EDT -4 0'
    config:
      oc-system-ext:enable-secret: 'admin'
      oc-system-ext:console-exec-timeout-seconds: '600'
      domain-name: 'cisco.com'
      hostname: 's1'
      login-banner: |
        This is line 1.
        This is line 2.
        This is the last line.
      motd-banner: |
        This is line 1.
        This is line 2.
        This is the last line.
    dns:
      servers:
        server:
          - address: '8.8.8.8'
            config:
              address: '8.8.8.8'
              port: '53'  # always 53 for ios
          - address: '8.8.4.4'
            config:
              address: '8.8.4.4'
              port: '53'  # always 53 for ios
    logging:  # facility must be same for all in IOS
      console:  # set console and monitor
        config: { }
        selectors:
          selector:
            - config:
                facility: 'SYSLOG'
                severity: 'INFORMATIONAL'  # logging console & logging monitor
              facility: 'SYSLOG'
              severity: 'INFORMATIONAL'
      remote-servers:
        remote-server:
          - config:
              host: '10.0.0.1'  # logging host x.x.x.x
              remote-port: '514'
              source-address: '192.168.100.1'  # logging source-interface Loopback0; same for all servers
              oc-system-ext:use-vrf: 'abc'
            host: '10.0.0.1'
            selectors:
              selector:
                - config:
                    facility: 'SYSLOG'
                    severity: 'INFORMATIONAL'
                  facility: 'SYSLOG'
                  severity: 'INFORMATIONAL'
          - config:
              host: '10.0.0.2'  # logging host x.x.x.x
              remote-port: '514'
              source-address: '192.168.100.1'  # logging source-interface Loopback0; same for all servers
              oc-system-ext:use-vrf: 'default'
            host: '10.0.0.2'
            selectors:
              selector:
                - config:
                    facility: 'SYSLOG'
                    severity: 'INFORMATIONAL'
                  facility: 'SYSLOG'
                  severity: 'INFORMATIONAL'
    ntp:
      config:
        oc-system-ext:ntp-enable-logging: true
        enable-ntp-auth: true
        enabled: true  # true or false - removes or adds ntp servers
        ntp-source-address: '192.168.100.1'
      ntp-keys:
        ntp-key:
          - config:
              key-id: '1'
              key-type: 'NTP_AUTH_MD5'
              key-value: 'password1'
            key-id: '1'
          - config:
              key-id: '2'
              key-type: 'NTP_AUTH_MD5'
              key-value: 'password2'
            key-id: '2'
      servers:
        server:
          - address: '10.0.0.1'
#            oc-system-ext:ntp-use-vrf: ''
            config:
              oc-system-ext:ntp-auth-key-id: '1'
              address: '10.0.0.1'
              association-type: SERVER  # SERVER, PEER, POOL
              iburst: true
              port: '123'  # always 123 for ios
              prefer: false
              version: '4'
          - address: '10.0.0.2'
            oc-system-ext:ntp-use-vrf: 'abc'
            config:
              oc-system-ext:ntp-auth-key-id: '2'
              address: '10.0.0.2'
              association-type: SERVER  # SERVER, PEER, POOL
              iburst: true
              port: '123'  # always 123 for ios
              prefer: false
              version: '4'
    ssh-server:
      config:
        oc-system-ext:absolute-timeout-minutes: '1200'
        oc-system-ext:ssh-timeout: '60'  # ip ssh timeout
        oc-system-ext:ssh-source-interface: 'GigabitEthernet1/0'
        enable: true  #   adds line transport input ssh; must be enabled for this to work
        protocol-version: 'V2'  # ip ssh version 2
        rate-limit: '0'  # unsupported in ios
        session-limit: '16' # line session-limit 16
        timeout: '1800'  # seconds - line exec-timeout 30 0
