---
- name: OC System test
  hosts: nso
  gather_facts: no
  vars:
    ansible_connection: netconf
    ansible_network_os: ios
    ansible_user: "admin"
    ansible_password: "xxx"
    ansible_port: 2022
  tasks:
    - netconf_config:
        target: running
        content: "{{ lookup('file', './config_NETCONF.xml') }}"