mdd:openconfig:
  openconfig-interfaces:interfaces:
    interface:
      - config:
          description: 'Physical Interface 2/0'
          enabled: true
          mtu: '1500'
          name: 'GigabitEthernet2/0'
          type: 'ethernetCsmacd'
        openconfig-if-ethernet:ethernet:
          config:
            auto-negotiate: true
            enable-flow-control: false
        hold-time:
          config:
            down: '10'
            up: '0'
        name: 'GigabitEthernet2/0'
        subinterfaces:
          subinterface:
            - config:
                index: '0'
              index: '0'
              openconfig-if-ip:ipv4:
                addresses:
                  address:
                    - config:
                        ip: '10.2.0.1'
                        prefix-length: '24'
                      ip: '10.2.0.1'
                config:
                  dhcp-client: false
      - config:
          description: 'Physical Interface 2/1'
          enabled: true
          mtu: '1500'
          name: 'GigabitEthernet2/1'
          type: 'ethernetCsmacd'
        openconfig-if-ethernet:ethernet:
          config:
            auto-negotiate: true
            enable-flow-control: false
        hold-time:
          config:
            down: '10'
            up: '0'
        name: 'GigabitEthernet2/1'
        subinterfaces:
          subinterface:
            - config:
                index: '0'
              index: '0'
              openconfig-if-ip:ipv4:
                addresses:
                  address:
                    - config:
                        ip: '10.2.1.1'
                        prefix-length: '24'
                      ip: '10.2.1.1'
                config:
                  dhcp-client: false
  openconfig-network-instance:network-instances:
    network-instance:
      - name: 'default'
        config:
          enabled: true
          name: 'default'
          type: 'DEFAULT_INSTANCE'
        interfaces:
          interface:
            - id: 'GigabitEthernet2/0'
              config:
                id: 'GigabitEthernet2/0'
                interface: 'GigabitEthernet2/0'
                subinterface: '0'
            - id: 'GigabitEthernet2/1'
              config:
                id: 'GigabitEthernet2/1'
                interface: 'GigabitEthernet2/1'
                subinterface: '0'
        mpls:
          global:
            config:
              ttl-propagation: true  # or no mpls ip propagate-ttl
            interface-attributes:
              interface:
                - config:
                    interface-id: 'GigabitEthernet2/0'
                    mpls-enabled: true
                  interface-id: 'GigabitEthernet2/0'
                  interface-ref:
                    config:
                      interface: 'GigabitEthernet2/0'
                      subinterface: '0'
                - config:
                    interface-id: 'GigabitEthernet2/1'
                    mpls-enabled: true
                  interface-id: 'GigabitEthernet2/1'
                  interface-ref:
                    config:
                      interface: 'GigabitEthernet2/1'
                      subinterface: '0'
          signaling-protocols:
            ldp:
              global:
                config:
                  lsr-id: '10.2.0.1'  # mpls ldp router-id Loopback0
                graceful-restart:
                  config:
                    enabled: true  # if true, mpls ldp graceful-restart
              interface-attributes:
                config:
                  hello-holdtime: '15'  # mpls ldp discovery hello holdtime seconds
                  hello-interval: '5'  # mpls ldp discovery hello interval seconds
