mdd:openconfig:
  openconfig-interfaces:interfaces:
    interface:
      - config:
          description: 'Physical Interface 1/0'
          enabled: true
          mtu: '1500'
          name: 'GigabitEthernet1/0'
          type: 'ethernetCsmacd'
        openconfig-if-ethernet:ethernet:
          config:
            auto-negotiate: true
            enable-flow-control: false
        hold-time:
          config:
            down: '10'
            up: '0'
        name: 'GigabitEthernet1/0'
        subinterfaces:
          subinterface:
            - config:
                index: '0'
              index: '0'
              openconfig-if-ip:ipv4:
                addresses:
                  address:
                    - config:
                        ip: '10.1.0.1'
                        prefix-length: '24'
                      ip: '10.1.0.1'
                config:
                  dhcp-client: false
      - config:
          description: 'Physical Interface 1/1'
          enabled: true
          mtu: '1500'
          name: 'GigabitEthernet1/1'
          type: 'ethernetCsmacd'
        openconfig-if-ethernet:ethernet:
          config:
            auto-negotiate: true
            enable-flow-control: false
        hold-time:
          config:
            down: '10'
            up: '0'
        name: 'GigabitEthernet1/1'
        subinterfaces:
          subinterface:
            - config:
                index: '0'
              index: '0'
              openconfig-if-ip:ipv4:
                addresses:
                  address:
                    - config:
                        ip: '10.1.1.2'
                        prefix-length: '24'
                      ip: '10.1.1.2'
                config:
                  dhcp-client: false
      - config:
          description: 'Physical Interface 1/2'
          enabled: true
          mtu: '1500'
          name: 'GigabitEthernet1/2'
          type: 'ethernetCsmacd'
        openconfig-if-ethernet:ethernet:
          config:
            auto-negotiate: true
        hold-time:
          config:
            down: '10'
            up: '0'
        name: 'GigabitEthernet1/2'
        subinterfaces:
          subinterface:
            - config:
                description: 'Sub interface 100'
                enabled: true
                index: '100'
              index: '100'
              openconfig-if-ip:ipv4:
                addresses:
                  address:
                    - config:
                        ip: '192.168.100.1'
                        prefix-length: '24'
                      ip: '192.168.100.1'
                config:
                  dhcp-client: false
                  enabled: true
                  mtu: '1500'
                proxy-arp:
                  config:
                    mode: DISABLE
              openconfig-vlan:vlan:
                config:
                  vlan-id: '100'
            - config:
                description: 'Sub interface 200'
                enabled: true
                index: '200'
              index: '200'
              openconfig-if-ip:ipv4:
                addresses:
                  address:
                    - config:
                        ip: '192.168.200.2'
                        prefix-length: '24'
                      ip: '192.168.200.2'
                config:
                  dhcp-client: false
                  enabled: true
                  mtu: '1500'
                proxy-arp:
                  config:
                    mode: DISABLE
              openconfig-vlan:vlan:
                config:
                  vlan-id: '200'
  openconfig-network-instance:network-instances:
    network-instance:
      - name: 'default'
        config:
          enabled: true
          name: 'default'
          type: 'DEFAULT_INSTANCE'
        interfaces:
          interface:
            - id: 'GigabitEthernet1/0'
              config:
                id: 'GigabitEthernet1/0'
                interface: 'GigabitEthernet1/0'
                subinterface: '0'
        protocols:
          protocol:
            - identifier: 'STATIC'
              name: 'DEFAULT'
              config:
                identifier: 'STATIC'
                name: 'DEFAULT'
              static-routes:
                static:
                  - prefix: '30.0.0.0/24'
                    config:
                      prefix: '30.0.0.0/24'
                    next-hops:
                      next-hop:
                        - config:
                            index: '##10.1.0.100##'
                            next-hop: '10.1.0.100'
                          index: '##10.1.0.100##'
                  - prefix: '40.0.0.0/24'
                    config:
                      prefix: '40.0.0.0/24'
                    next-hops:
                      next-hop:
                        - config:
                            index: '##10.1.0.100##'
                            next-hop: '10.1.0.100'
                          index: '##10.1.0.100##'
                  - prefix: '50.0.0.0/24'
                    config:
                      prefix: '50.0.0.0/24'
                    next-hops:
                      next-hop:
                        - config:
                            index: '##10.1.0.100##'
                            next-hop: '10.1.0.100'
                          index: '##10.1.0.100##'
      - name: 'abc'
        config:
          name: 'abc'
          type: 'L3VRF'
          enabled: true
          enabled-address-families:
            - 'IPV4'
        interfaces:
          interface:
            - id: 'GigabitEthernet1/1'
              config:
                id: 'GigabitEthernet1/1'
                interface: 'GigabitEthernet1/1'
                subinterface: '0'
            - id: 'GigabitEthernet1/2.100'
              config:
                id: 'GigabitEthernet1/2.100'
                interface: 'GigabitEthernet1/2'
                subinterface: '100'
            - id: 'GigabitEthernet1/2.200'
              config:
                id: 'GigabitEthernet1/2.200'
                interface: 'GigabitEthernet1/2'
                subinterface: '200'
        protocols:
          protocol:
            - identifier: 'STATIC'
              name: 'DEFAULT'
              config:
                identifier: 'STATIC'
                name: 'DEFAULT'
              static-routes:
                static:
                  - prefix: '0.0.0.0/0'
                    config:
                      prefix: '0.0.0.0/0'
                    next-hops:
                      next-hop:
                        - config:
                            index: '##10.1.1.1##'
                            next-hop: '10.1.1.1'
                          index: '##10.1.1.1##'
                  - prefix: '172.16.0.0/24'
                    config:
                      prefix: '172.16.0.0/24'
                    next-hops:
                      next-hop:
                        - config:
                            index: '##10.1.1.1##'
                            next-hop: '10.1.1.1'
                          index: '##10.1.1.1##'
            - identifier: 'STATIC'
              name: 'DEFAULT'
              config:
                identifier: 'STATIC'
                name: 'DEFAULT'
              static-routes:
                static:
                  - prefix: '172.17.0.0/24'
                    config:
                      prefix: '172.17.0.0/24'
                    next-hops:
                      next-hop:
                        - config:
                            index: '##10.16.0.1##'
                            next-hop: '10.16.0.1'
                            metric: '100'
                          index: '##10.16.0.1##'
            - identifier: 'STATIC'
              name: 'DEFAULT'
              config:
                identifier: 'STATIC'
                name: 'DEFAULT'
              static-routes:
                static:
                  - prefix: '172.18.0.0/24'
                    config:
                      prefix: '172.18.0.0/24'
                    next-hops:
                      next-hop:
                        - config:
                            index: '##10.16.0.1##'
                            next-hop: '10.16.0.1'
                            metric: '100'
                          index: '##10.16.0.1##'
