mdd:openconfig:
  openconfig-interfaces:interfaces:
    interface:
      - config:
          description: 'Physical Interface 1/0'
          enabled: true
          mtu: '1500'
          name: 'GigabitEthernet1/0'
          type: 'ethernetCsmacd'
        openconfig-if-ethernet:ethernet:
          config:
            auto-negotiate: true
            enable-flow-control: false
        hold-time:
          config:
            down: '10'
            up: '0'
        name: 'GigabitEthernet1/0'
        subinterfaces:
          subinterface:
            - config:
                index: '0'
              index: '0'
              openconfig-if-ip:ipv4:
                addresses:
                  address:
                    - config:
                        ip: '10.1.0.1'
                        prefix-length: '24'
                      ip: '10.1.0.1'
                config:
                  dhcp-client: false
      - config:
          description: 'Physical Interface 1/1'
          enabled: true
          mtu: '1500'
          name: 'GigabitEthernet1/1'
          type: 'ethernetCsmacd'
        openconfig-if-ethernet:ethernet:
          config:
            auto-negotiate: true
            enable-flow-control: false
        hold-time:
          config:
            down: '10'
            up: '0'
        name: 'GigabitEthernet1/1'
        subinterfaces:
          subinterface:
            - config:
                index: '0'
              index: '0'
              openconfig-if-ip:ipv4:
                addresses:
                  address:
                    - config:
                        ip: '10.1.1.2'
                        prefix-length: '24'
                      ip: '10.1.1.2'
                config:
                  dhcp-client: false
      - config:
          description: 'Physical Interface 1/2'
          enabled: true
          mtu: '1500'
          name: 'GigabitEthernet1/2'
          type: 'ethernetCsmacd'
        openconfig-if-ethernet:ethernet:
          config:
            auto-negotiate: true
        hold-time:
          config:
            down: '10'
            up: '0'
        name: 'GigabitEthernet1/2'
        subinterfaces:
          subinterface:
            - config:
                description: 'Sub interface 100'
                enabled: true
                index: '100'
              index: '100'
              openconfig-if-ip:ipv4:
                addresses:
                  address:
                    - config:
                        ip: '192.168.100.1'
                        prefix-length: '24'
                      ip: '192.168.100.1'
                config:
                  dhcp-client: false
                  enabled: true
                  mtu: '1500'
                proxy-arp:
                  config:
                    mode: DISABLE
              openconfig-vlan:vlan:
                config:
                  vlan-id: '100'
            - config:
                description: 'Sub interface 200'
                enabled: true
                index: '200'
              index: '200'
              openconfig-if-ip:ipv4:
                addresses:
                  address:
                    - config:
                        ip: '192.168.200.2'
                        prefix-length: '24'
                      ip: '192.168.200.2'
                config:
                  dhcp-client: false
                  enabled: true
                  mtu: '1500'
                proxy-arp:
                  config:
                    mode: DISABLE
              openconfig-vlan:vlan:
                config:
                  vlan-id: '200'
  openconfig-network-instance:network-instances:
    network-instance:
      - name: 'default'
        config:
          enabled: true
          name: 'default'
          type: 'DEFAULT_INSTANCE'
        interfaces:
          interface:
            - id: 'GigabitEthernet1/0'
              config:
                id: 'GigabitEthernet1/0'
                interface: 'GigabitEthernet1/0'
                subinterface: '0'
      - name: 'abc'
        config:
          name: 'abc'
          type: 'L3VRF'
          enabled: true
          enabled-address-families:
            - 'IPV4'
        interfaces:
          interface:
            - id: 'GigabitEthernet1/1'
              config:
                id: 'GigabitEthernet1/1'
                interface: 'GigabitEthernet1/1'
                subinterface: '0'
            - id: 'GigabitEthernet1/2.100'
              config:
                id: 'GigabitEthernet1/2.100'
                interface: 'GigabitEthernet1/2'
                subinterface: '100'
            - id: 'GigabitEthernet1/2.200'
              config:
                id: 'GigabitEthernet1/2.200'
                interface: 'GigabitEthernet1/2'
                subinterface: '200'
  openconfig-acl:acl:
    acl-sets:
      acl-set:
        - config:
            description: 'external to internal'
            name: 'external-ingress'
            type: 'ACL_IPV4'
          name: 'external-ingress'
          type: 'ACL_IPV4'
          acl-entries:
            acl-entry:
              - actions:
                  config:
                    forwarding-action: 'ACCEPT'
                    log-action: 'LOG_NONE'
                config:
                  description: 'ssh'
                  sequence-id: '10'
                ipv4:
                  config:
                    destination-address: '0.0.0.0/0'
                    protocol: 'IP_TCP'
                    source-address: '0.0.0.0/0'
                sequence-id: '10'
                transport:
                  config:
                    destination-port: '22'
              - actions:
                  config:
                    forwarding-action: 'ACCEPT'
                    log-action: 'LOG_NONE'
                config:
                  description: 'established TCP traffic'
                  sequence-id: '20'
                ipv4:
                  config:
                    destination-address: '0.0.0.0/0'
                    protocol: 'IP_TCP'
                    source-address: '0.0.0.0/0'
                sequence-id: '20'
                transport:
                  config:
                    destination-port: '1024..65535'
                    tcp-flags:
                      - 'TCP_ACK'
                      - 'TCP_RST'
              - actions:
                  config:
                    forwarding-action: 'DROP'
                    log-action: 'LOG_SYSLOG'
                config:
                  description: 'drop log other packets'
                  sequence-id: '30'
                ipv4:
                  config:
                    destination-address: '0.0.0.0/0'
                    source-address: '0.0.0.0/0'
                sequence-id: '30'
        - config:
            description: 'bogons-aggregated'
            name: 'deny-bogons-ingress'
            type: 'ACL_IPV4'
          name: 'deny-bogons-ingress'
          type: 'ACL_IPV4'
          acl-entries:
            acl-entry:
              - actions:
                  config:
                    forwarding-action: 'DROP'
                    log-action: 'LOG_SYSLOG'
                config:
                  description: 'bogons'
                  sequence-id: '10'
                ipv4:
                  config:
                    destination-address: '0.0.0.0/0'
                    source-address: '0.0.0.0/8'
                sequence-id: '10'
              - actions:
                  config:
                    forwarding-action: 'DROP'
                    log-action: 'LOG_SYSLOG'
                config:
                  description: 'bogons'
                  sequence-id: '20'
                ipv4:
                  config:
                    destination-address: '0.0.0.0/0'
                    source-address: '10.0.0.0/8'
                sequence-id: '20'
              - actions:
                  config:
                    forwarding-action: 'DROP'
                    log-action: 'LOG_SYSLOG'
                config:
                  description: 'bogons'
                  sequence-id: '30'
                ipv4:
                  config:
                    destination-address: '0.0.0.0/0'
                    source-address: '100.64.0.0/10'
                sequence-id: '30'
              - actions:
                  config:
                    forwarding-action: 'DROP'
                    log-action: 'LOG_SYSLOG'
                config:
                  description: 'bogons'
                  sequence-id: '40'
                ipv4:
                  config:
                    destination-address: '0.0.0.0/0'
                    source-address: '127.0.0.0/8'
                sequence-id: '40'
              - actions:
                  config:
                    forwarding-action: 'DROP'
                    log-action: 'LOG_SYSLOG'
                config:
                  description: 'bogons'
                  sequence-id: '50'
                ipv4:
                  config:
                    destination-address: '0.0.0.0/0'
                    source-address: '169.254.0.0/16'
                sequence-id: '50'
        - config:
            description: 'bogons-aggregated'
            name: 'deny-bogons-egress'
            type: 'ACL_IPV4'
          name: 'deny-bogons-egress'
          type: 'ACL_IPV4'
          acl-entries:
            acl-entry:
              - actions:
                  config:
                    forwarding-action: 'DROP'
                    log-action: 'LOG_SYSLOG'
                config:
                  description: 'bogons'
                  sequence-id: '10'
                ipv4:
                  config:
                    destination-address: '0.0.0.0/8'
                    source-address: '0.0.0.0/0'
                sequence-id: '10'
              - actions:
                  config:
                    forwarding-action: 'DROP'
                    log-action: 'LOG_SYSLOG'
                config:
                  description: 'bogons'
                  sequence-id: '20'
                ipv4:
                  config:
                    destination-address: '10.0.0.0/8'
                    source-address: '0.0.0.0/0'
                sequence-id: '20'
              - actions:
                  config:
                    forwarding-action: 'DROP'
                    log-action: 'LOG_SYSLOG'
                config:
                  description: 'bogons'
                  sequence-id: '30'
                ipv4:
                  config:
                    destination-address: '100.64.0.0/10'
                    source-address: '0.0.0.0/0'
                sequence-id: '30'
              - actions:
                  config:
                    forwarding-action: 'DROP'
                    log-action: 'LOG_SYSLOG'
                config:
                  description: 'bogons'
                  sequence-id: '40'
                ipv4:
                  config:
                    destination-address: '127.0.0.0/8'
                    source-address: '0.0.0.0/0'
                sequence-id: '40'
              - actions:
                  config:
                    forwarding-action: 'DROP'
                    log-action: 'LOG_SYSLOG'
                config:
                  description: 'bogons'
                  sequence-id: '50'
                ipv4:
                  config:
                    destination-address: '169.254.0.0/16'
                    source-address: '0.0.0.0/0'
                sequence-id: '50'
              - actions:
                  config:
                    forwarding-action: 'DROP'
                    log-action: 'LOG_SYSLOG'
                config:
                  description: 'bogons'
                  sequence-id: '60'
                ipv4:
                  config:
                    destination-address: '172.16.0.0/12'
                    source-address: '0.0.0.0/0'
                sequence-id: '60'
              - actions:
                  config:
                    forwarding-action: 'DROP'
                    log-action: 'LOG_SYSLOG'
                config:
                  description: 'bogons'
                  sequence-id: '70'
                ipv4:
                  config:
                    destination-address: '192.0.0.0/24'
                    source-address: '0.0.0.0/0'
                sequence-id: '70'
              - actions:
                  config:
                    forwarding-action: 'DROP'
                    log-action: 'LOG_SYSLOG'
                config:
                  description: 'bogons'
                  sequence-id: '80'
                ipv4:
                  config:
                    destination-address: '192.0.2.0/24'
                    source-address: '0.0.0.0/0'
                sequence-id: '80'
              - actions:
                  config:
                    forwarding-action: 'DROP'
                    log-action: 'LOG_SYSLOG'
                config:
                  description: 'bogons'
                  sequence-id: '90'
                ipv4:
                  config:
                    destination-address: '192.168.0.0/16'
                    source-address: '0.0.0.0/0'
                sequence-id: '90'
              - actions:
                  config:
                    forwarding-action: 'DROP'
                    log-action: 'LOG_SYSLOG'
                config:
                  description: 'bogons'
                  sequence-id: '100'
                ipv4:
                  config:
                    destination-address: '198.18.0.0/15'
                    source-address: '0.0.0.0/0'
                sequence-id: '100'
              - actions:
                  config:
                    forwarding-action: 'DROP'
                    log-action: 'LOG_SYSLOG'
                config:
                  description: 'bogons'
                  sequence-id: '110'
                ipv4:
                  config:
                    destination-address: '198.51.100.0/24'
                    source-address: '0.0.0.0/0'
                sequence-id: '110'
              - actions:
                  config:
                    forwarding-action: 'DROP'
                    log-action: 'LOG_SYSLOG'
                config:
                  description: 'bogons'
                  sequence-id: '120'
                ipv4:
                  config:
                    destination-address: '203.0.113.0/24'
                    source-address: '0.0.0.0/0'
                sequence-id: '120'
              - actions:
                  config:
                    forwarding-action: 'DROP'
                    log-action: 'LOG_SYSLOG'
                config:
                  description: 'bogons'
                  sequence-id: '130'
                ipv4:
                  config:
                    destination-address: '224.0.0.0/3'
                    source-address: '0.0.0.0/0'
                sequence-id: '130'
              - actions:
                  config:
                    forwarding-action: 'ACCEPT'
                config:
                  description: 'bogons'
                  sequence-id: '140'
                ipv4:
                  config:
                    destination-address: '0.0.0.0/0'
                    source-address: '0.0.0.0/0'
                sequence-id: '140'
    interfaces:
      interface:
        - config:
            id: 'GigabitEthernet1/0'
          id: 'GigabitEthernet1/0'
          ingress-acl-sets:
            ingress-acl-set:
              - config:
                  set-name: 'external-ingress'
                  type: 'ACL_IPV4'
                set-name: 'external-ingress'
                type: 'ACL_IPV4'
          interface-ref:
            config:
              interface: 'GigabitEthernet1/0'
              subinterface: '0'
        - config:
            id: 'GigabitEthernet1/1'
          id: 'GigabitEthernet1/1'
          egress-acl-sets:
            egress-acl-set:
              - config:
                  set-name: 'deny-bogons-egress'
                  type: 'ACL_IPV4'
                set-name: 'deny-bogons-egress'
                type: 'ACL_IPV4'
          ingress-acl-sets:
            ingress-acl-set:
              - config:
                  set-name: 'deny-bogons-ingress'
                  type: 'ACL_IPV4'
                set-name: 'deny-bogons-ingress'
                type: 'ACL_IPV4'
          interface-ref:
            config:
              interface: 'GigabitEthernet1/1'
              subinterface: '0'
        - config:
            id: 'GigabitEthernet1/2.100'
          id: 'GigabitEthernet1/2.100'
          ingress-acl-sets:
            ingress-acl-set:
              - config:
                  set-name: 'deny-bogons-ingress'
                  type: 'ACL_IPV4'
                set-name: 'deny-bogons-ingress'
                type: 'ACL_IPV4'
          interface-ref:
            config:
              interface: 'GigabitEthernet1/2'
              subinterface: '100'
        - config:
            id: 'GigabitEthernet1/2.200'
          id: 'GigabitEthernet1/2.200'
          ingress-acl-sets:
            ingress-acl-set:
              - config:
                  set-name: 'deny-bogons-ingress'
                  type: 'ACL_IPV4'
                set-name: 'deny-bogons-ingress'
                type: 'ACL_IPV4'
          interface-ref:
            config:
              interface: 'GigabitEthernet1/2'
              subinterface: '200'
