oc-interfaces-nso:oc-interfaces-nso:
- device: ''
  openconfig-interfaces:
    interfaces:
      interface:
      - aggregation:
          config:
            lag-type: ''
            min-links: ''
          state:
            lag-speed: ''
            lag-type: ''
            member:
            - '['
            - ']'
            min-links: ''
          switched-vlan:
            config:
              access-vlan: ''
              interface-mode: ''
              native-vlan: ''
              trunk-vlans:
              - '['
              - ']'
            state:
              access-vlan: ''
              interface-mode: ''
              native-vlan: ''
              trunk-vlans:
              - '['
              - ']'
        config:
          description: ''
          enabled: 'True'
          loopback-mode: 'False'
          mtu: ''
          name: ''
          type: ''
        ethernet:
          config:
            aggregate-id: ''
            auto-negotiate: 'True'
            duplex-mode: ''
            enable-flow-control: 'False'
            mac-address: ''
            port-speed: ''
          poe:
            config:
              enabled: 'True'
            state:
              enabled: 'True'
              power-class: ''
              power-used: ''
          state:
            auto-negotiate: 'True'
            counters:
              in-8021q-frames: ''
              in-crc-errors: ''
              in-fragment-frames: ''
              in-jabber-frames: ''
              in-mac-control-frames: ''
              in-mac-pause-frames: ''
              in-oversize-frames: ''
              out-8021q-frames: ''
              out-mac-control-frames: ''
              out-mac-pause-frames: ''
            duplex-mode: ''
            enable-flow-control: 'False'
            hw-mac-address: ''
            mac-address: ''
            negotiated-duplex-mode: ''
            negotiated-port-speed: ''
            port-speed: ''
          switched-vlan:
            config:
              access-vlan: ''
              interface-mode: ''
              native-vlan: ''
              trunk-vlans:
              - '['
              - ']'
            state:
              access-vlan: ''
              interface-mode: ''
              native-vlan: ''
              trunk-vlans:
              - '['
              - ']'
        hold-time:
          config:
            down: '0'
            up: '0'
          state:
            down: '0'
            up: '0'
        name: ''
        routed-vlan:
          config:
            vlan: ''
          ipv4:
            addresses:
              address:
              - config:
                  ip: ''
                  prefix-length: ''
                ip: ''
                state:
                  ip: ''
                  origin: ''
                  prefix-length: ''
                vrrp:
                  vrrp-group:
                  - config:
                      accept-mode: 'False'
                      advertisement-interval: '100'
                      preempt: 'True'
                      preempt-delay: '0'
                      priority: '100'
                      virtual-address:
                      - '['
                      - ']'
                      virtual-router-id: ''
                    interface-tracking:
                      config:
                        priority-decrement: '0'
                        track-interface:
                        - '['
                        - ']'
                      state:
                        priority-decrement: '0'
                        track-interface:
                        - '['
                        - ']'
                    state:
                      accept-mode: 'False'
                      advertisement-interval: '100'
                      current-priority: ''
                      preempt: 'True'
                      preempt-delay: '0'
                      priority: '100'
                      virtual-address:
                      - '['
                      - ']'
                      virtual-router-id: ''
                    virtual-router-id: ''
            config:
              dhcp-client: 'False'
              enabled: 'True'
              mtu: ''
            neighbors:
              neighbor:
              - config:
                  ip: ''
                  link-layer-address: ''
                ip: ''
                state:
                  ip: ''
                  link-layer-address: ''
                  origin: ''
            proxy-arp:
              config:
                mode: DISABLE
              state:
                mode: DISABLE
            state:
              counters:
                in-discarded-pkts: ''
                in-error-pkts: ''
                in-forwarded-octets: ''
                in-forwarded-pkts: ''
                in-octets: ''
                in-pkts: ''
                out-discarded-pkts: ''
                out-error-pkts: ''
                out-forwarded-octets: ''
                out-forwarded-pkts: ''
                out-octets: ''
                out-pkts: ''
              dhcp-client: 'False'
              enabled: 'True'
              mtu: ''
            unnumbered:
              config:
                enabled: 'False'
              interface-ref:
                config:
                  interface: ''
                  subinterface: ''
                state:
                  interface: ''
                  subinterface: ''
              state:
                enabled: 'False'
          ipv6:
            addresses:
              address:
              - config:
                  ip: ''
                  prefix-length: ''
                ip: ''
                state:
                  ip: ''
                  origin: ''
                  prefix-length: ''
                  status: ''
                vrrp:
                  vrrp-group:
                  - config:
                      accept-mode: 'False'
                      advertisement-interval: '100'
                      preempt: 'True'
                      preempt-delay: '0'
                      priority: '100'
                      virtual-address:
                      - '['
                      - ']'
                      virtual-link-local: ''
                      virtual-router-id: ''
                    interface-tracking:
                      config:
                        priority-decrement: '0'
                        track-interface:
                        - '['
                        - ']'
                      state:
                        priority-decrement: '0'
                        track-interface:
                        - '['
                        - ']'
                    state:
                      accept-mode: 'False'
                      advertisement-interval: '100'
                      current-priority: ''
                      preempt: 'True'
                      preempt-delay: '0'
                      priority: '100'
                      virtual-address:
                      - '['
                      - ']'
                      virtual-router-id: ''
                    virtual-router-id: ''
            config:
              dhcp-client: 'False'
              dup-addr-detect-transmits: '1'
              enabled: 'True'
              mtu: ''
            neighbors:
              neighbor:
              - config:
                  ip: ''
                  link-layer-address: ''
                ip: ''
                state:
                  ip: ''
                  is-router: ''
                  link-layer-address: ''
                  neighbor-state: ''
                  origin: ''
            router-advertisement:
              config:
                interval: ''
                lifetime: ''
                suppress: 'False'
              state:
                interval: ''
                lifetime: ''
                suppress: 'False'
            state:
              counters:
                in-discarded-pkts: ''
                in-error-pkts: ''
                in-forwarded-octets: ''
                in-forwarded-pkts: ''
                in-octets: ''
                in-pkts: ''
                out-discarded-pkts: ''
                out-error-pkts: ''
                out-forwarded-octets: ''
                out-forwarded-pkts: ''
                out-octets: ''
                out-pkts: ''
              dhcp-client: 'False'
              dup-addr-detect-transmits: '1'
              enabled: 'True'
              mtu: ''
            unnumbered:
              config:
                enabled: 'False'
              interface-ref:
                config:
                  interface: ''
                  subinterface: ''
                state:
                  interface: ''
                  subinterface: ''
              state:
                enabled: 'False'
          state:
            vlan: ''
        state:
          admin-status: ''
          counters:
            carrier-transitions: ''
            in-broadcast-pkts: ''
            in-discards: ''
            in-errors: ''
            in-fcs-errors: ''
            in-multicast-pkts: ''
            in-octets: ''
            in-unicast-pkts: ''
            in-unknown-protos: ''
            last-clear: ''
            out-broadcast-pkts: ''
            out-discards: ''
            out-errors: ''
            out-multicast-pkts: ''
            out-octets: ''
            out-unicast-pkts: ''
          description: ''
          enabled: 'True'
          ifindex: ''
          last-change: ''
          loopback-mode: 'False'
          mtu: ''
          name: ''
          oper-status: ''
          type: ''
        subinterfaces:
          subinterface:
          - config:
              description: ''
              enabled: 'True'
              index: '0'
            index: ''
            ipv4:
              addresses:
                address:
                - config:
                    ip: ''
                    prefix-length: ''
                  ip: ''
                  state:
                    ip: ''
                    origin: ''
                    prefix-length: ''
                  vrrp:
                    vrrp-group:
                    - config:
                        accept-mode: 'False'
                        advertisement-interval: '100'
                        preempt: 'True'
                        preempt-delay: '0'
                        priority: '100'
                        virtual-address:
                        - '['
                        - ']'
                        virtual-router-id: ''
                      interface-tracking:
                        config:
                          priority-decrement: '0'
                          track-interface:
                          - '['
                          - ']'
                        state:
                          priority-decrement: '0'
                          track-interface:
                          - '['
                          - ']'
                      state:
                        accept-mode: 'False'
                        advertisement-interval: '100'
                        current-priority: ''
                        preempt: 'True'
                        preempt-delay: '0'
                        priority: '100'
                        virtual-address:
                        - '['
                        - ']'
                        virtual-router-id: ''
                      virtual-router-id: ''
              config:
                dhcp-client: 'False'
                enabled: 'True'
                mtu: ''
              neighbors:
                neighbor:
                - config:
                    ip: ''
                    link-layer-address: ''
                  ip: ''
                  state:
                    ip: ''
                    link-layer-address: ''
                    origin: ''
              proxy-arp:
                config:
                  mode: DISABLE
                state:
                  mode: DISABLE
              state:
                counters:
                  in-discarded-pkts: ''
                  in-error-pkts: ''
                  in-forwarded-octets: ''
                  in-forwarded-pkts: ''
                  in-octets: ''
                  in-pkts: ''
                  out-discarded-pkts: ''
                  out-error-pkts: ''
                  out-forwarded-octets: ''
                  out-forwarded-pkts: ''
                  out-octets: ''
                  out-pkts: ''
                dhcp-client: 'False'
                enabled: 'True'
                mtu: ''
              unnumbered:
                config:
                  enabled: 'False'
                interface-ref:
                  config:
                    interface: ''
                    subinterface: ''
                  state:
                    interface: ''
                    subinterface: ''
                state:
                  enabled: 'False'
            ipv6:
              addresses:
                address:
                - config:
                    ip: ''
                    prefix-length: ''
                  ip: ''
                  state:
                    ip: ''
                    origin: ''
                    prefix-length: ''
                    status: ''
                  vrrp:
                    vrrp-group:
                    - config:
                        accept-mode: 'False'
                        advertisement-interval: '100'
                        preempt: 'True'
                        preempt-delay: '0'
                        priority: '100'
                        virtual-address:
                        - '['
                        - ']'
                        virtual-link-local: ''
                        virtual-router-id: ''
                      interface-tracking:
                        config:
                          priority-decrement: '0'
                          track-interface:
                          - '['
                          - ']'
                        state:
                          priority-decrement: '0'
                          track-interface:
                          - '['
                          - ']'
                      state:
                        accept-mode: 'False'
                        advertisement-interval: '100'
                        current-priority: ''
                        preempt: 'True'
                        preempt-delay: '0'
                        priority: '100'
                        virtual-address:
                        - '['
                        - ']'
                        virtual-router-id: ''
                      virtual-router-id: ''
              config:
                dhcp-client: 'False'
                dup-addr-detect-transmits: '1'
                enabled: 'True'
                mtu: ''
              neighbors:
                neighbor:
                - config:
                    ip: ''
                    link-layer-address: ''
                  ip: ''
                  state:
                    ip: ''
                    is-router: ''
                    link-layer-address: ''
                    neighbor-state: ''
                    origin: ''
              router-advertisement:
                config:
                  interval: ''
                  lifetime: ''
                  suppress: 'False'
                state:
                  interval: ''
                  lifetime: ''
                  suppress: 'False'
              state:
                counters:
                  in-discarded-pkts: ''
                  in-error-pkts: ''
                  in-forwarded-octets: ''
                  in-forwarded-pkts: ''
                  in-octets: ''
                  in-pkts: ''
                  out-discarded-pkts: ''
                  out-error-pkts: ''
                  out-forwarded-octets: ''
                  out-forwarded-pkts: ''
                  out-octets: ''
                  out-pkts: ''
                dhcp-client: 'False'
                dup-addr-detect-transmits: '1'
                enabled: 'True'
                mtu: ''
              unnumbered:
                config:
                  enabled: 'False'
                interface-ref:
                  config:
                    interface: ''
                    subinterface: ''
                  state:
                    interface: ''
                    subinterface: ''
                state:
                  enabled: 'False'
            state:
              admin-status: ''
              counters:
                carrier-transitions: ''
                in-broadcast-pkts: ''
                in-discards: ''
                in-errors: ''
                in-fcs-errors: ''
                in-multicast-pkts: ''
                in-octets: ''
                in-unicast-pkts: ''
                in-unknown-protos: ''
                last-clear: ''
                out-broadcast-pkts: ''
                out-discards: ''
                out-errors: ''
                out-multicast-pkts: ''
                out-octets: ''
                out-unicast-pkts: ''
              description: ''
              enabled: 'True'
              ifindex: ''
              index: '0'
              last-change: ''
              name: ''
              oper-status: ''
            vlan:
              config:
                vlan-id: ''
              state:
                vlan-id: ''
