name: NSO-Services CI
on:
  pull_request_review:
    types: [ submitted ]
    branches: [ main ]
jobs:
  test:
    runs-on: self-hosted
    if: github.event.review.state == 'approved'
    steps:
      - run: echo "The name of your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - name: Create Archive of the mdd directory
        run: |
          tar -czvf mdd.tgz mdd
      - name: update ubuntu
        run: sudo apt-get update
      - name: install sshpass
        run: sudo apt-get install sshpass -y
      - name: Install PIP requirements
        run: pip install -r ./test/requirements.txt
      - name: Install Collections
        run: ansible-galaxy collection install -r ./test/requirements.yml
      - name: Delete CML
        run: ansible-playbook ./test/clean-cml.yml
        env:
          CML_LAB: ${{ secrets.CML_LAB }}
          CML_HOST: ${{ secrets.CML_HOST }}
          CML_USERNAME: ${{ secrets.CML_USERNAME }}
          CML_PASSWORD: ${{ secrets.CML_PASSWORD }}
          ANSIBLE_CONFIG: ${{ github.workspace }}/test/ansible.cfg
      - name: Build CML
        run: ansible-playbook ./test/build-cml.yml
        env:
          CML_LAB_FILE: ./arch/test_lab.yaml
          CML_LAB: ${{ secrets.CML_LAB }}
          CML_HOST: ${{ secrets.CML_HOST }}
          CML_USERNAME: ${{ secrets.CML_USERNAME }}
          CML_PASSWORD: ${{ secrets.CML_PASSWORD }}
          ANSIBLE_CONFIG: ${{ github.workspace }}/test/ansible.cfg
      - name: Write contents of nso IP file to envars
        run: |
          cat ${{ github.workspace }}/nso_host.txt >> $GITHUB_ENV
      - name: Write contents of xe1 IP file to envars
        run: |
          cat ${{ github.workspace }}/xe1_host.txt >> $GITHUB_ENV
      - name: Write contents of xeswitch1 IP file to envars
        run: |
          cat ${{ github.workspace }}/xeswitch1_host.txt >> $GITHUB_ENV
      - name: Build NSO
        run: ansible-playbook ./test/build-nso.yml
        env:
          CML_LAB: ${{ secrets.CML_LAB }}
          CML_HOST: ${{ secrets.CML_HOST }}
          CML_USERNAME: ${{ secrets.CML_USERNAME }}
          CML_PASSWORD: ${{ secrets.CML_PASSWORD }}
          ANSIBLE_CONFIG: ${{ github.workspace }}/test/ansible.cfg
      - name: Run Tests
        run: |
          cd ./test/tests
          FILES=$(ls ./*.yml)
          for PLAYBOOK in $FILES
          do
          echo $PLAYBOOK
          ansible-playbook $PLAYBOOK
          done
        env:
          CML_LAB: ${{ secrets.CML_LAB }}
          CML_HOST: ${{ secrets.CML_HOST }}
          CML_USERNAME: ${{ secrets.CML_USERNAME }}
          CML_PASSWORD: ${{ secrets.CML_PASSWORD }}
          ANSIBLE_CONFIG: ${{ github.workspace }}/test/ansible.cfg
          NSO_HOST: ${{ env.NSO_HOST }}
          NSO_USERNAME: ${{ secrets.NSO_USERNAME }}
          NSO_PASSWORD: ${{ secrets.NSO_PASSWORD }}
          NSO_OS_USERNAME: ${{ secrets.NSO_OS_USERNAME }}
          NSO_OS_PASSWORD: ${{ secrets.NSO_OS_PASSWORD }}
          XE1_HOST: ${{ env.XE1_HOST }}
          XESWITCH1_HOST: ${{ env.XESWITCH1_HOST }}
          NSO_DEVICES_USERNAME: ${{ secrets.NSO_DEVICES_USERNAME }}
          NSO_DEVICES_PASSWORD: ${{ secrets.NSO_DEVICES_PASSWORD }}
      - name: Delete CML
        if: always()
        run: ansible-playbook ./test/clean-cml.yml
        env:
          CML_LAB: ${{ secrets.CML_LAB }}
          CML_HOST: ${{ secrets.CML_HOST }}
          CML_USERNAME: ${{ secrets.CML_USERNAME }}
          CML_PASSWORD: ${{ secrets.CML_PASSWORD }}
          ANSIBLE_CONFIG: ${{ github.workspace }}/test/ansible.cfg
