name: GitHub Actions Demo
on:
  pull_request_review:
    types: [ submitted ]
    branches: [ main ]
jobs:
  test:
    runs-on: self-hosted
    if: github.event.review.state == 'approved'
    steps:
      - run: echo "The name of your branch is ${{ github.head_ref }} and your repository is ${{ github.repository }}."
      - run: echo "github.ref_name is ${{ github.ref_name }}."
      - run: echo "github.head_ref is ${{ github.head_ref }}."
      - run: echo "github.base_ref is ${{ github.base_ref }}."
      - run: echo "github.ref is ${{ github.ref }}."
      - run: echo "github.event is ${{ github.event }}."
      - run: echo "github * context is ${{ github.* }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - name: update ubuntu
        run: sudo apt-get update
      - name: install sshpass
        run: sudo apt-get install sshpass -y
      - name: Install PIP requirements
        run: pip install -r ./test/requirements.txt
      - name: Install Collections
        run: ansible-galaxy collection install -r ./test/requirements.yml
      - name: Delete CML
        run: ansible-playbook ./test/clean-cml.yml
        env:
          CML_LAB: ${{ secrets.CML_LAB }}
          CML_HOST: ${{ secrets.CML_HOST }}
          CML_USERNAME: ${{ secrets.CML_USERNAME }}
          CML_PASSWORD: ${{ secrets.CML_PASSWORD }}
          ANSIBLE_CONFIG: ${{ github.workspace }}/test/ansible.cfg
      - name: Build CML
        run: ansible-playbook ./test/build-cml.yml
        env:
          CML_LAB_FILE: ./arch/test_lab.yaml
          CML_LAB: ${{ secrets.CML_LAB }}
          CML_HOST: ${{ secrets.CML_HOST }}
          CML_USERNAME: ${{ secrets.CML_USERNAME }}
          CML_PASSWORD: ${{ secrets.CML_PASSWORD }}
          ANSIBLE_CONFIG: ${{ github.workspace }}/test/ansible.cfg
      - name: Build NSO
        run: ansible-playbook ./test/build-nso.yml
        env:
          CML_LAB: ${{ secrets.CML_LAB }}
          CML_HOST: ${{ secrets.CML_HOST }}
          CML_USERNAME: ${{ secrets.CML_USERNAME }}
          CML_PASSWORD: ${{ secrets.CML_PASSWORD }}
          GITHUB_BRANCH: ${{ github.ref }}
          ANSIBLE_CONFIG: ${{ github.workspace }}/test/ansible.cfg
      - name: Run Tests
        run: |
          cd ./test/tests
          FILES=$(ls ./*.yml)
          for PLAYBOOK in $FILES
          do
          echo $PLAYBOOK
          ansible-playbook $PLAYBOOK
          done
        env:
          CML_LAB: ${{ secrets.CML_LAB }}
          CML_HOST: ${{ secrets.CML_HOST }}
          CML_USERNAME: ${{ secrets.CML_USERNAME }}
          CML_PASSWORD: ${{ secrets.CML_PASSWORD }}
          ANSIBLE_CONFIG: ${{ github.workspace }}/test/ansible.cfg
      - name: Delete CML
        if: always()
        run: ansible-playbook ./test/clean-cml.yml
        env:
          CML_LAB: ${{ secrets.CML_LAB }}
          CML_HOST: ${{ secrets.CML_HOST }}
          CML_USERNAME: ${{ secrets.CML_USERNAME }}
          CML_PASSWORD: ${{ secrets.CML_PASSWORD }}
          ANSIBLE_CONFIG: ${{ github.workspace }}/test/ansible.cfg
